config/routes.rb
Rails.application.routes.draw do

  root :to => 'pages#home'

  resources :users
  resources :lists do
    resources :tasks
  end

  get '/login' =>'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'


end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :tasks
  belongs_to :user
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :lists
  has_many :tasks, :through => :lists
  has_secure_password
  validates :username, :email, :presence => true, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :fetch_user

  private
  def fetch_user
    # Search for a user by their user id if we can find one in the session hash.
    if session[:user_id].present?
      @current_user = User.find_by :id => session[:user_id]

      # Clear out the session user_id if no user is found.
      session[:user_id] = nil unless @current_user
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = @current_user.lists
    @tasks = @current_user.tasks

  end

  def new
    @list = List.new
  end

  def create
    list = List.create list_params
    list.user_id = @current_user.id
    list.save
    #redirect_to list_task_path(task.list, task)
    redirect_to list_tasks_path(list)

  end

  def edit
    @list = List.find params[:id]
  end

  def update
    list = List.find params[:id]
    list.update list_params
     redirect_to :back #when we change anything in the editing form redirect to the same page
  end

  def show
    @lists = @current_user.lists
    @list = List.find(params[:id])
    @task = Task.new
  end

  def destroy
    list = List.find(params[:id])
    list.destroy
    redirect_to lists_path
    #redirect_to :back #when we change anything in the editing form redirect to the same page
    # try to test it:

    # if @current_user.lists.any?
    #   redirect_to "lists", list_tasks_path(@current_user.lists.first)
    # else
    #   redirect_to "lists", lists_path
    # end
  end

  private

  def list_params
    params.require(:list).permit(:title, :category)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
      user = User.find_by :username => params[:username]
      if user.present? && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to lists_path
      else
        redirect_to login_path
      end
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = @current_user.tasks
    #copy from show
    @lists = @current_user.lists
    # @task = Task.find_by :id => params[:id]
    @list = List.find params[:list_id]
  end

  def new
    @list = List.find params[:list_id]
    @task = Task.new
  end

  def create
      # task = Task.create task_params
      task = Task.new task_params
      list = List.find params[:list_id]
      if task.save
        list.tasks << task
        redirect_to list_tasks_path(list)
      else
        redirect_to :back
      end
      # list = List.find params[:list_id] # this is the url stored in a var
      # list.tasks << task # apending the task in the task in that list
      # redirect_to :back #when we change anything in the editing form redirect to the same page
  end

  def edit
    @task = Task.find params[:id]
    @list = List.find params[:list_id]

  end

  def update
      task = Task.find params[:id]
      task.update task_params
      redirect_to list_task_path(task.list, task)
  end

  def show
    @lists = @current_user.lists
    @task = Task.find_by :id => params[:id]
    @list = List.find params[:list_id]
  end

  def destroy
    task = Task.find params[:id] # storing in a var the task we want to delete. We are looking for the task by id
    task.destroy  # to delete the var
    redirect_to :back # the url
  end

  private
  def task_params
    params.require(:task).permit(:title, :status, :description)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      UserMailer.welcome(@user).deliver_now
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end



  def edit
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header id="mainnav" class="navbar navbar-default mainnav">
      <div class="container">
        <div class="row">
        	<!-- logo -->
          <div class="col-xs-12 col-sm-3 logo logo-image">
            <%= image_tag 'todo.png', :class => 'logo-img' %>
          </div>
          <!--  end logo -->
          <nav class="col-xs-12 col-sm-4 mainnav ">
            <ul class="nav navbar-nav">
              <li><%= link_to 'Home', root_path %></li>
            <% if @current_user.present? %>
                  <% if @current_user.lists.any? %>
                    <li><%= link_to "lists", list_tasks_path(@current_user.lists.first) %></li>
                  <% else %>
                    <li><%= link_to "lists", lists_path %></li>
                  <% end %>
                  <li><%= link_to "Log Out #{ @current_user.username}", login_path, :method => :delete %></li>
            <% else %>
              <li><%= link_to "Sign Up", new_user_path %></li>
            </ul>
          </nav>
          <!-- end nav -->
          <div class="col-xs-12 col-sm-5 login">
            <%= form_tag '/login' do %>
              <%= text_field_tag :username,  nil, :autofocus =>true, placeholder: "username" %>
              <%= password_field_tag :password %>
              <%= submit_tag 'login' %>
            <% end %>
          </div>
             <% end %>
        </div>
      </div>
      <!-- end container -->
  </header>
<div class="container main yield">
  <%= yield %>
</div>
</body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, :autofocus => true, :required => true, :class => 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :category %>
      <%= f.text_field :category, :required => true, :class => 'form-control' %>
    </div>
    <%= f.submit %>
<% end %>

app/views/lists/_form_list_edit.html.erb
<div class="edit-list-form">
  <%= form_for @list do |f| %>
  <div class="edit form-group form-inline">
    <%= button_tag(type: "submit", class: "edit-btn", name: "commit", value: "conceal") do %>
      <span class="glyphicon glyphicon-repeat"></span>
    <% end %>
    <%= f.text_field :title, placeholder: "title", :autofocus => true, :required => true, :class => 'form-control' %>
  </div>
  <% end %>
</div>

app/views/lists/_form_list_new.html.erb
<div class="index-form">
  <%= form_for List.new do |f| %>
      <div class="create form-group form-inline">
        <%= f.submit "+" %>
        <%= f.text_field :title, placeholder: "title", :autofocus => true, :required => true, :class => 'form-control' %>
      </div>
    <% end %>
</div>

app/views/lists/_form_task_new.html.erb
<%= form_for [@list, Task.new] do |f| %>
  <div class="form-group form-inline new-tasks">
      <%= f.submit "+" %>
      <%= f.text_field :title, placeholder: "add task",  :autofocus => true, :required => true, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.text_area :description, placeholder: "description", :class => 'form-control' %>
  </div>
<% end %>

app/views/lists/_index.html.erb
  <div class="index">
    <h1>Lists</h1>
    <div class="control">
      <%= render :partial => 'form_list_new' %>
    </div>
    <div class="index-list">
        <% @lists.each do |list| %>
        <ul>
          <li><%= link_to list.title, list_path(list) %></li>
        </ul>
        <% end %>
      </div>
  </div>

app/views/lists/_show.html.erb
<div class="index">
  <h1>List</h1>
  <%= render :partial => 'form_list_edit' %>
  <%= render :partial => 'form_task_new' %>
  <% @list.tasks.each do |task| %>
  <ul>
    <li><%= link_to task.title, list_task_path(@list, task) %></li>
  </ul>
  <% end %>
</div>

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<%= render :partial => 'form' %>

app/views/lists/index.html.erb
<!-- <div class="container"> -->
  <div class="col-xs-12 col-md-6 col-md-offset-3 start-lists index">
    <h1>Lists</h1>
        <%= render :partial => 'form_list_new' %>
    <% @lists.each do |list| %>
    <ul>
      <li><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span><%= link_to list.title, list_tasks_path(list) %></li>
    </ul>
    <% end %>
  </div>
<!-- </div> -->

app/views/lists/new.html.erb
<h1>Lists#new</h1>

app/views/lists/show.html.erb
<div class="">
    <div class="col-xs-12 col-md-6 index">
      <%= render :partial => 'index' %>
    </div>
    <div class="col-xs-12 col-md-6 show">
      <%= render :partial => 'show' %>
    </div>
</div>

app/views/pages/home.html.erb
<div class="home-header">
  <div class="container">
    <h1>Turn your browser </br> into the ultimate</br>to do list with todo.</h1>
  </div>
</div>
<!-- end home-header -->

<div class="jumbotron text-center">
  <div class="container">
  </div>

</div>
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <h3>Column 1</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit...</p>
      <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...</p>
    </div>
    <div class="col-sm-4">
      <h3>Column 2</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit...</p>
      <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...</p>
    </div>
    <div class="col-sm-4">
      <h3>Column 3</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit...</p>
      <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...</p>
    </div>
  </div>
</div>
<footer class="main-footer">
  <div class="container">
  <div class="row">
    <div class="col-sm-4">
      <h3>Column 1</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit...</p>
      <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...</p>
    </div>
    <div class="col-sm-4">
      <h3>Column 2</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit...</p>
      <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...</p>
    </div>
    <div class="col-sm-4">
      <h3>Column 3</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit...</p>
      <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...</p>
    </div>
  </div>
</div>
</footer>

app/views/session/new.html.erb
<h1>Login</h1>
<%= form_tag '/login' do %>
  <%= label_tag :username %>
  <%= text_field_tag :username,  nil, :autofocus =>true %>
  <%= label_tag :password %>
  <%= password_field_tag :password %>
  <%= submit_tag 'login' %>
<% end %>

app/views/tasks/_edit_list.html.erb
<div class="edit-list-form-task">
  <%= form_for @list do |f| %>
  <div class="edit form-group form-inline">
    <%= button_tag(type: "submit", class: "edit-btn", name: "commit", value: "conceal") do %>
      <span class="glyphicon glyphicon-repeat"></span>
    <% end %>
    <%= link_to '<span class="glyphicon glyphicon-check" aria-hidden="true"></span>'.html_safe, list_path(@list.id), :method => :delete, :data => { :confirm => "Are you sure?" } %>
    <%= f.text_field :title, placeholder: "title", :autofocus => true, :required => true, :class => 'form-control' %>
  </div>
  <% end %>
</div>

app/views/tasks/_form.html.erb
<%= form_for [@list, @task] do |f| %>
  <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, :autofocus => true, :required => true, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, :class => 'form-control' %>
  </div>
  <%= f.submit 'Save' %>
<% end %>

app/views/tasks/_form_list.html.erb
<div class="index-form form-inline">
  <%= form_for List.new do |f| %>
        <%= f.submit "+" %>
        <%= f.text_field :title, placeholder: "add list", :autofocus => true, :required => true, :class => 'form-control' %>

  <% end %>
</div>

app/views/tasks/_form_task_new.html.erb
<div class="form-group form-inline new-tasks">
  <%= form_for [@list, Task.new] do |f| %>
      <%= f.submit "+" %>
      <%= f.text_field :title, placeholder: "add task",  :autofocus => true, :required => true, :class => 'form-control' %>
  <% end %>
  </div>

app/views/tasks/_index_list.html.erb
<div class="index-list-task">
    <%= render :partial => 'form_list' %>
    <ul>
        <% @lists.each do |list| %>

          <li><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
            <%= link_to list.title, list_tasks_path(list) %></li>
        <% end %>
    </ul>
</div>

app/views/tasks/_new_list.html.erb
<h1>Lists#edi aqui</h1>
<%= form_for List.new do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, :autofocus => true, :required => true, :class => 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :category %>
      <%= f.text_field :category, :required => true, :class => 'form-control' %>
    </div>
    <%= f.submit %>sadfasd
<% end %>

app/views/tasks/_show_list.html.erb
<div class="form">
<%= render :partial => 'form_task_new' %>
</div>
<% @list.tasks.each do |task| %>
<ul class= task-list>
  <li>
      <%= link_to '<span class="glyphicon glyphicon-check" aria-hidden="true"></span>'.html_safe, list_task_path(@list, task), :method => :delete, :data => { :confirm => "Are you sure?" } %>
      <%=task.title %>
  </li>
</ul>
<% end %>

app/views/tasks/index.html.erb
<h1><%= @current_user.username %> List</h1>
<div class="main-container">
    <div class="col-xs-12 col-sm-4 index_list_show">
      <%= render :partial => 'index_list' %>
    </div>
    <div class="col-xs-12 col-sm-8 edit_list_show">
    <%= render :partial => 'edit_list' %>
      <%= render :partial => 'show_list' %>
    </div>
  </div>

app/views/tasks/new.html.erb
<h1>Tasks#new</h1>
<%= render :partial => 'form' %>

app/views/tasks/show.html.erb
<div class="main-container">
    <div class="col-xs-12 col-sm-4 index_list_show">
      <%= render :partial => 'index_list' %>
    </div>
    <div class="col-xs-12 col-sm-8 edit_list_show">
    <%= render :partial => 'edit_list' %>
      <%= render :partial => 'show_list' %>

    </div>
  </div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<div class="container sign-form form">
  <div class="col-xs-4 col-md-offset-3">
    <hgroup>
      <h1>Sign Up</h1>
  </hgroup>
  <% if @user.errors.any? %>
    <ol>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ol>
  <% end %>
<%= form_for @user do |f| %>
    <div class="group">
      <%= f.text_field :username, :autofocus => true, :required => true%>
      <span class="highlight"></span><span class="bar"></span>
      <%= f.label :username %>
    </div>
    <div class="group">
      <%= f.text_field :email, :autofocus => true, :required => true %>
      <span class="highlight"></span><span class="bar"></span>
      <%= f.label :email %>
    </div>
    <div class="group">
      <%= f.password_field :password, :required => true  %>
      <span class="highlight"></span><span class="bar"></span>
      <%= f.label :password %>
    </div>
    <div class="group">
      <%= f.password_field :password_confirmation, :required => true  %>
      <span class="highlight"></span><span class="bar"></span>
      <%= f.label :password_confirmation %>
    </div>
    <%= f.submit "Sign Up", :class =>'submit' %>
<% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>